Rails.application.routes.draw do
  scope "", as: "whatsapp_plugin" do
    scope "projects/:project_id", as: "project" do
      get "whatsapp", to: "whatsapp#index", as: "whatsapp"
      get "contactos", to: "contactos#index", as: "contactos"
      get "contactos/menu", to: "contactos/menus#show", as: "contactos_menu"
      get "contactos/historial", to: "contactos#history", as: "contactos_history"
      get "contactos/new", to: "contactos#new", as: "contactos_new"
      get "contactos/duplicates", to: "contactos#duplicates", as: "contactos_duplicates"
      get "contactos/export", to: "contactos#export", as: "contactos_export"
      get "contactos/table_settings", to: "contactos#table_settings", as: "contactos_table_settings"
      post "contactos/table_settings", to: "contactos#update_table_settings", as: "contactos_table_settings_update"
      post "contactos/import", to: "contactos#import", as: "contactos_import"
      post "contactos/fields", to: "contactos#create_field", as: "contactos_fields"
      get "contactos/fields_panel", to: "contactos#fields_panel", as: "contactos_fields_panel"
      post "contactos/fields/order", to: "contactos#update_fields_order", as: "contactos_fields_order"
      post "contactos/fields/form_order", to: "contactos#update_form_order", as: "contactos_fields_form_order"
      patch "contactos/fields/:id", to: "contactos#update_field", as: "contactos_field"
      delete "contactos/fields/:id", to: "contactos#destroy_field"
      get "contactos/tags", to: "contactos#tags_index", as: "contactos_tags"
      post "contactos/tags", to: "contactos#tags_upsert", as: "contactos_tags_upsert"
      patch "contactos/tags/:id/color", to: "contactos#tags_color", as: "contactos_tags_color"
      patch "contactos/tags/:id/rename", to: "contactos#tags_rename", as: "contactos_tags_rename"
      delete "contactos/tags/:id", to: "contactos#tags_destroy", as: "contactos_tags_destroy"
      get "contactos/:id/edit_panel", to: "contactos#edit_panel", as: "contactos_edit_panel"
      get "contactos/:id/files", to: "contactos#files_index", as: "contactos_files"
      post "contactos/:id/files", to: "contactos#files_create", as: "contactos_files_create"
      delete "contactos/:id/files/:file_id", to: "contactos#files_destroy", as: "contactos_files_destroy"
      post "contactos/:id/call_activity", to: "contactos#call_activity", as: "contactos_call_activity"
      post "contactos/pause_activity", to: "contactos#pause_activity", as: "contactos_pause_activity"
      get "contactos/:id/call_history", to: "contactos#call_history_index", as: "contactos_call_history"
      get "contactos/:id/call_history/:history_id/audio", to: "contactos#call_history_audio", as: "contactos_call_history_audio"
      delete "contactos/:id/call_history/:history_id", to: "contactos#call_history_destroy", as: "contactos_call_history_destroy"
      post "contactos/:id/recorder_log", to: "contactos#recorder_log", as: "contactos_recorder_log"
      post "contactos/:id/recorder_preview", to: "contactos#recorder_preview_create", as: "contactos_recorder_preview"
      get "contactos/:id/recorder_preview/:token", to: "contactos#recorder_preview_show", as: "contactos_recorder_preview_file"
      get "contactos/:id", to: "contactos#show", as: "contacto"
      post "contactos", to: "contactos#create", as: "contactos_create"
      patch "contactos/:id", to: "contactos#update", as: "contactos_update"
      post "contactos/bulk_assign", to: "contactos#bulk_assign", as: "contactos_bulk_assign"
      delete "contactos/:id", to: "contactos#destroy", as: "contactos_destroy"
      post "whatsapp/messages", to: "whatsapp#create_message", as: "whatsapp_messages"
      get "whatsapp/messages/:id/media", to: "whatsapp#message_media", as: "whatsapp_message_media"
      get "whatsapp/media_files", to: "whatsapp#media_files", as: "whatsapp_media_files"
      delete "whatsapp/media_files/:id", to: "whatsapp#destroy_media_file", as: "whatsapp_media_file_destroy"
      post "whatsapp/media_files/bulk_delete", to: "whatsapp#bulk_destroy_media_files", as: "whatsapp_media_files_bulk_destroy"
      post "whatsapp/waha/webhook", to: "whatsapp#waha_webhook", as: "whatsapp_waha_webhook"
      post "whatsapp/images", to: "whatsapp#create_image_message", as: "whatsapp_images"
      post "whatsapp/videos", to: "whatsapp#create_video_message", as: "whatsapp_videos"
      post "whatsapp/files", to: "whatsapp#create_file_message", as: "whatsapp_files"
      post "whatsapp/typing/start", to: "whatsapp#start_typing", as: "whatsapp_typing_start"
      post "whatsapp/typing/stop", to: "whatsapp#stop_typing", as: "whatsapp_typing_stop"
      post "whatsapp/activity_note", to: "whatsapp#create_activity_note", as: "whatsapp_activity_note"
      delete "whatsapp/messages", to: "whatsapp#destroy_chat", as: "whatsapp_chat"
      post "whatsapp/debug", to: "whatsapp#debug_log", as: "whatsapp_debug"
      get "whatsapp/contacts/profile", to: "whatsapp#contact_profile", as: "whatsapp_contact_profile"
      post "whatsapp/contacts/profile", to: "whatsapp#upsert_contact_profile", as: "whatsapp_contact_profile_save"
      get "whatsapp/chats/search", to: "whatsapp#search_chats", as: "whatsapp_chats_search"
      post "whatsapp/chats/:id/favorite", to: "whatsapp#toggle_favorite", as: "whatsapp_chat_favorite"
      post "whatsapp/chats/:id/read", to: "whatsapp#mark_chat_read", as: "whatsapp_chat_read"
      post "whatsapp/chats/:id/ia_flow", to: "whatsapp#update_ai_flow", as: "whatsapp_chat_ia_flow"
      get "whatsapp/work_package_types", to: "whatsapp#work_package_types", as: "whatsapp_work_package_types"
      get "whatsapp/boards", to: "whatsapp#boards", as: "whatsapp_boards"
      get "whatsapp/boards/:id/lists", to: "whatsapp#board_lists", as: "whatsapp_board_lists"
      post "whatsapp/boards/add_card", to: "whatsapp#board_add_card", as: "whatsapp_board_add_card"
      get "whatsapp/boards/cards", to: "whatsapp#board_cards", as: "whatsapp_board_cards"
      delete "whatsapp/boards/cards/:id", to: "whatsapp#destroy_board_card", as: "whatsapp_board_card_destroy"
      get "whatsapp/work_packages/related", to: "whatsapp#related_work_packages", as: "whatsapp_related_work_packages"
      post "whatsapp/work_packages", to: "whatsapp#create_related_work_package", as: "whatsapp_work_packages"
      delete "whatsapp/work_packages/:id", to: "whatsapp#destroy_related_work_package", as: "whatsapp_work_package_destroy"
      delete "whatsapp/work_packages/:id/unlink",
             to: "whatsapp#unlink_related_work_package",
             as: "whatsapp_work_package_unlink"
      get "whatsapp/work_packages/:id/details",
          to: "whatsapp#work_package_details",
          as: "whatsapp_work_package_details"
      get "whatsapp/work_packages/:id/chat",
          to: "whatsapp#work_package_chat",
          as: "whatsapp_work_package_chat"
      get "whatsapp/work_packages/:id/statuses",
          to: "whatsapp#work_package_statuses",
          as: "whatsapp_work_package_statuses"
      post "whatsapp/settings", to: "whatsapp#update_settings", as: "whatsapp_settings"
      post "whatsapp/templates", to: "whatsapp#create_template", as: "whatsapp_templates"
      patch "whatsapp/templates/:id", to: "whatsapp#update_template", as: "whatsapp_template"
      delete "whatsapp/templates/:id", to: "whatsapp#destroy_template", as: "whatsapp_template_destroy"
      get "whatsapp/templates/:id/media", to: "whatsapp#template_media", as: "whatsapp_template_media"
      post "whatsapp/waha/sessions", to: "whatsapp#create_waha_session", as: "whatsapp_waha_sessions"
      post "whatsapp/waha/sessions/:session/start", to: "whatsapp#start_waha_session", as: "whatsapp_waha_session_start"
      get "whatsapp/waha/sessions/:session", to: "whatsapp#waha_session_status", as: "whatsapp_waha_session_status"
      get "whatsapp/waha/sessions/:session/qr", to: "whatsapp#qr_waha_session", as: "whatsapp_waha_session_qr"
      delete "whatsapp/waha/sessions/:session", to: "whatsapp#delete_waha_session", as: "whatsapp_waha_session_delete"
      get "whatsapp/admin/connections", to: "whatsapp#admin_connections", as: "whatsapp_admin_connections"
      post "whatsapp/admin/connections/:connection_project_id/limit",
           to: "whatsapp#update_admin_connection_limit",
           as: "whatsapp_admin_connection_limit"
      post "whatsapp/chats", to: "whatsapp#create_chat", as: "whatsapp_chats"

      get "email", to: "email_email#index", as: "email"
      get "email/settings", to: "email_email#settings", as: "email_settings"
      post "email/settings", to: "email_email#update_settings", as: "email_settings_update"
      get "email/templates", to: "email_email#templates", as: "email_templates"
      get "email/templates/new", to: "email_email#new_template", as: "email_templates_new"
      post "email/templates", to: "email_email#create_template", as: "email_templates_create"
      get "email/templates/:id/edit", to: "email_email#edit_template", as: "email_template_edit"
      patch "email/templates/:id", to: "email_email#update_template", as: "email_template_update"
      delete "email/templates/:id", to: "email_email#destroy_template", as: "email_template_destroy"
      delete "email/templates/:template_id/attachments/:id",
             to: "email_email#destroy_template_attachment",
             as: "email_template_attachment_destroy"
      get "email/send", to: "email_email#send_form", as: "email_send"
      post "email/send", to: "email_email#send_email", as: "email_send_create"
      get "email/recent_deliveries", to: "email_email#recent_deliveries", as: "email_recent_deliveries"
      post "email/preview", to: "email_email#preview", as: "email_preview"
      get "email/track/open/:token.png", to: "email_email#open_track", as: "email_open_track"
      get "email/history", to: "email_email#history", as: "email_history"
      delete "email/history/bulk", to: "email_email#destroy_history_bulk", as: "email_history_bulk_destroy"
      delete "email/history/pending", to: "email_email#destroy_history_pending", as: "email_history_pending_destroy"
      delete "email/history/:id", to: "email_email#destroy_history_delivery", as: "email_history_delivery_destroy"
      get "email/flows", to: "email_email#flows", as: "email_flows"
      get "email/flows/history", to: "email_email#flows_history", as: "email_flows_history"
      get "email/flows/history/data", to: "email_email#flow_history_data", as: "email_flows_history_data"
      get "email/flows/data", to: "email_email#flow_data", as: "email_flows_data"
      get "email/flows/list", to: "email_email#flow_list", as: "email_flows_list"
      post "email/flows", to: "email_email#save_flow", as: "email_flows_save"
      post "email/flows/ia_agents", to: "email_email#ia_agents", as: "email_flows_ia_agents"
      post "email/flows/run", to: "email_email#run_flow", as: "email_flows_run"
      delete "email/flows/:flow_id", to: "email_email#delete_flow", as: "email_flows_delete"
      post "email/flows/webhook/:token", to: "email_email#webhook_flow", as: "email_flows_webhook"
      delete "email/flows/events", to: "email_email#clear_flow_events", as: "email_flows_events_clear"
    end
  end
end
